In [1]:
import pandas as pd
import nltk

In [2]:
d=pd.read_csv(r"C:\Users\HP\PycharmProjectsAI\NLP\spam (2).csv", encoding='latin-1')
d
df = d['v2'][10]
df

"I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today."

In [3]:
from nltk.tokenize import word_tokenize,sent_tokenize

word = word_tokenize(df)
word

['I',
 "'m",
 'gon',
 'na',
 'be',
 'home',
 'soon',
 'and',
 'i',
 'do',
 "n't",
 'want',
 'to',
 'talk',
 'about',
 'this',
 'stuff',
 'anymore',
 'tonight',
 ',',
 'k',
 '?',
 'I',
 "'ve",
 'cried',
 'enough',
 'today',
 '.']

In [4]:
sent = sent_tokenize(df)
sent

["I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k?",
 "I've cried enough today."]

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
tf = TfidfVectorizer()

x = tf.fit_transform(sent).toarray()
x

array([[0.26726124, 0.26726124, 0.26726124, 0.26726124, 0.        ,
        0.26726124, 0.        , 0.26726124, 0.26726124, 0.26726124,
        0.26726124, 0.26726124, 0.26726124, 0.26726124, 0.        ,
        0.26726124, 0.        , 0.26726124],
       [0.        , 0.        , 0.        , 0.        , 0.5       ,
        0.        , 0.5       , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.5       ,
        0.        , 0.5       , 0.        ]])

In [6]:
co=CountVectorizer()
y=co.fit_transform(sent).toarray()
y

array([[1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0]])

In [7]:
df = d['v2'][100]
df

'Okay name ur price as long as its legal! Wen can I pick them up? Y u ave x ams xx'

In [8]:
words = word_tokenize(df)
words

['Okay',
 'name',
 'ur',
 'price',
 'as',
 'long',
 'as',
 'its',
 'legal',
 '!',
 'Wen',
 'can',
 'I',
 'pick',
 'them',
 'up',
 '?',
 'Y',
 'u',
 'ave',
 'x',
 'ams',
 'xx']

In [9]:
sent = sent_tokenize(df)
sent

['Okay name ur price as long as its legal!',
 'Wen can I pick them up?',
 'Y u ave x ams xx']

In [10]:
a = tf.fit_transform(sent).toarray()
a

array([[0.        , 0.60302269, 0.        , 0.        , 0.30151134,
        0.30151134, 0.30151134, 0.30151134, 0.30151134, 0.        ,
        0.30151134, 0.        , 0.        , 0.30151134, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.4472136 , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.4472136 ,
        0.        , 0.4472136 , 0.4472136 , 0.        , 0.4472136 ,
        0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.57735027]])

In [11]:
b = co.fit_transform(sent).toarray()
b

array([[0, 2, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [12]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

for word in words:
    print(word,"  ===  ",ps.stem(word))

Okay   ===   okay
name   ===   name
ur   ===   ur
price   ===   price
as   ===   as
long   ===   long
as   ===   as
its   ===   it
legal   ===   legal
!   ===   !
Wen   ===   wen
can   ===   can
I   ===   i
pick   ===   pick
them   ===   them
up   ===   up
?   ===   ?
Y   ===   y
u   ===   u
ave   ===   ave
x   ===   x
ams   ===   am
xx   ===   xx


In [13]:
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
wl = WordNetLemmatizer()

for word in words:
    print(word, "  ==  ", wl.lemmatize(word))

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


Okay   ==   Okay
name   ==   name
ur   ==   ur
price   ==   price
as   ==   a
long   ==   long
as   ==   a
its   ==   it
legal   ==   legal
!   ==   !
Wen   ==   Wen
can   ==   can
I   ==   I
pick   ==   pick
them   ==   them
up   ==   up
?   ==   ?
Y   ==   Y
u   ==   u
ave   ==   ave
x   ==   x
ams   ==   am
xx   ==   xx


In [14]:
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('punkt_tab')

sw = set(stopwords.words('english'))

new_words = [word for word in words if word not in sw]
print(new_words)

['Okay', 'name', 'ur', 'price', 'long', 'legal', '!', 'Wen', 'I', 'pick', '?', 'Y', 'u', 'ave', 'x', 'ams', 'xx']


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [17]:
df = new_words
df

['Okay',
 'name',
 'ur',
 'price',
 'long',
 'legal',
 '!',
 'Wen',
 'I',
 'pick',
 '?',
 'Y',
 'u',
 'ave',
 'x',
 'ams',
 'xx']

In [18]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

co = CountVectorizer()
tf = TfidfVectorizer()

x= co.fit_transform(df).toarray()
x

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [19]:
y = tf.fit_transform(df).toarray()
y

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])